[project]
name = "datn-signlanguagedetection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "mediapipe>=0.10.33",
    "numpy>=2.4.4",
    "opencv-python>=4.13.0.92",
    "pandas>=3.0.2",
    "yt-dlp>=2026.3.17",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
]
